version: '3.7'
services:
  postfix:
    build: .
    image: gitlab.mbit-consultants.com:5678/infra/postfix:latest
    container_name: postfix
    restart: unless-stopped
    environment:
      - HOSTNAME=postfix.local
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - ./main.cf:/etc/postfix/main.cf
    #  - ./sasl_passwd:/etc/postfix/sasl_passwd
    #  - ./entrypoint.sh:/entrypoint.sh
    networks:
      - postfix-net

networks:
  postfix-net:
    driver: bridge
